### ISSUE TITLE
lein install fails

### ISSUE THREAD

**Issue by norton** [oliyh/martian#85]
I'm curious what version of lein, clojure, and java is supported.

lein install fails
```
 lein install
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
 Module build order:
   martian
   martian-clj-http-lite
   martian-httpkit
   martian-test
   martian-cljs-http
   martian-clj-http
   martian-re-frame
------------------------------------------------------------------------
 Building martian 0.1.13-SNAPSHOT (base,system,user,provided,dev)
------------------------------------------------------------------------
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Compiling 1 source files to /Users/joe/tmp/martian/core/target/classes
warning: [options] bootstrap class path not set in conjunction with -source 8
1 warning
Created /Users/joe/tmp/martian/core/target/martian-0.1.13-SNAPSHOT.jar
Wrote /Users/joe/tmp/martian/core/pom.xml
Installed jar and pom into local repo.
------------------------------------------------------------------------
 Building martian-clj-http-lite 0.1.13-SNAPSHOT (base,system,user,provided,dev)
------------------------------------------------------------------------
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Error encountered performing task 'install' with profile(s): 'base,system,user,provided-martian-clj-http-lite,dev-martian-clj-http-lite'
java.lang.IllegalArgumentException: Bad artifact coordinates martian:martian:jar::version, expected format is <groupId>:<artifactId>[:<extension>[:<classifier>]]:<version>
	at org.eclipse.aether.artifact.DefaultArtifact.<init>(DefaultArtifact.java:77)
	at org.eclipse.aether.artifact.DefaultArtifact.<init>(DefaultArtifact.java:60)
	at cemerick.pomegranate.aether$artifact.invokeStatic(aether.clj:244)
	at cemerick.pomegranate.aether$artifact.invoke(aether.clj:242)
	at cemerick.pomegranate.aether$dependency.invokeStatic(aether.clj:253)
	at cemerick.pomegranate.aether$dependency.invoke(aether.clj:246)
	at cemerick.pomegranate.aether$coords__GT_Dependencies$fn__364.invoke(aether.clj:704)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
```

I am using the following:

```
lein version
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Leiningen 2.9.3 on Java 14.0.1 OpenJDK 64-Bit Server VM
```

**Comment by oliyh** [comment]
Hi,

It builds for me on
```
Leiningen 2.9.0 on Java 11.0.7 OpenJDK 64-Bit Server VM
```

Are you able to `cd clj-http-lite && lein install`? If so then I think it's just an issue with [lein-modules](https://github.com/jcrossley3/lein-modules). It looks a bit unmaintained but I see there are several forks which are ahead, it's possible one of them might fix it?

**Comment by norton** [comment]
It still fails at the top-level with the following version

`~/bin/lein version
Leiningen 2.9.0 on Java 11.0.2 OpenJDK 64-Bit Server VM
`

`cd clj-http-lite && lein install` does work.

It seems to be an issue with lein-modules.

**Comment by norton** [comment]
I will avoid lein-modules for the time being.  Thank you for the feedback.

**Comment by lvh** [comment]
FYI, this problem still exists. I looked at forks but didn't find anything that works. "Avoid lein-modules" isn't possible (well, unless that means "avoid developing martian" which I assume isn't the goal :)) -- the modules use `:version` as a version specifier in project.clj.  I'm working around it by specifying the latest SNAPSHOT explicitly in the subprojects.

**Comment by oliyh** [comment]
Agree, I ran into this too when I moved to a new laptop. What confuses me most is that it runs on CI, `circleci/clojure:lein-2.9.1-browsers` which has `Leiningen 2.9.1 on Java 11.0.6 OpenJDK 64-Bit Server VM`

**Comment by oliyh** [comment]
Data point: it works on `Leiningen 2.9.1 on Java 11.0.26 OpenJDK 64-Bit Server VM` too

**Comment by marksto** [comment]
Here's the actual fix: https://github.com/oliyh/martian/pull/226/commits/8bb9ebb5ee0278ac0b4f466608757aabd6ae2135 and https://github.com/oliyh/martian/pull/226/commits/8ac5cff2e9f68f8646a90188d6d121efaf61a4ae.
